In [191]:
# Why use NumPy?
import time
import numpy as np
x = np.random.random(100000000)
print(x)

[0.68226678 0.90173061 0.25748159 ... 0.651631   0.28000036 0.22483392]


In [206]:
# Case 1
start = time.time()
sum(x) / len(x)
print(time.time() - start)

7.122959613800049


In [205]:
# Case 2
start = time.time()
np.mean(x)
print(time.time() - start)

0.11775374412536621


### Creating and Saving Numpy NDArray

In [46]:
np_array = np.array([1,2,3,4,5])

print("dtype: ", np_array.dtype)
print("shape: ", np_array.shape)
print("size: ", np_array.size)
print("ndim: ", np_array.ndim)

dtype:  int32
shape:  (5,)
size:  5
ndim:  1


In [43]:
np_array_2 = np.array([[1,2,3,4,5], 
                       [6,7,8,9,10]])
print("dtype: ", np_array_2.dtype)
print("shape: ", np_array_2.shape)
print("size: ", np_array_2.size)
print("ndim: ", np_array_2.ndim)

dtype:  int32
shape:  (2, 5)
size:  10
ndim:  2


In [42]:
np_array_2 = np.array([[1,2,3,4,5], 
                       [6,7,8,9,'hello']])
print("dtype: ", np_array_2.dtype)
print("shape: ", np_array_2.shape)
print("size: ", np_array_2.size)
print("ndim: ", np_array_2.ndim)

dtype:  <U11
shape:  (2, 5)
size:  10
ndim:  2


In [48]:
np_array_2 = np.array([[1,2,3,4,5], 
                       ['h', 'e', 'l', 'l', 'o']])
print("dtype: ", np_array_2.dtype)
print("shape: ", np_array_2.shape)
print("size: ", np_array_2.size)
print("ndim: ", np_array_2.ndim)

# Numpy ndarray can hold only one type of data, as can be seen here
print("np_array_2: ", np_array_2)

dtype:  <U11
shape:  (2, 5)
size:  10
ndim:  2
np_array_2:  [['1' '2' '3' '4' '5']
 ['h' 'e' 'l' 'l' 'o']]


In [52]:
# We create a rank 1 ndarray that only contains strings
x = np.array(['Hello', 'World'])

# We print information about x
print('x = ', x)
print('shape:', x.shape)
print('type:', type(x))
print('dtype:', x.dtype)
print('ndim:', x.ndim)

x =  ['Hello' 'World']
shape: (2,)
type: <class 'numpy.ndarray'>
dtype: <U5
ndim: 1


### Using a 1-D Array to Demonstrate Upcasting in Numeric datatype

In [58]:
#Example 1.d - Using a 1-D Array of Int and Float

# We create a rank 1 ndarray that contains integers
x = np.array([1,2,3])

# We create a rank 1 ndarray that contains floats
y = np.array([1.0,2.0,3.0])

# We create a rank 1 ndarray that contains integers and floats
z = np.array([1, 2.5, 4])

# We print the dtype of each ndarray
print('The elements in x are of type:', x.dtype)
print('The elements in y are of type:', y.dtype)
print('The elements in z are of type:', z.dtype)

The elements in x are of type: int32
The elements in y are of type: float64
The elements in z are of type: float64


In [63]:
#Example 1.d - Using a 1-D Array of Int and Float

# We create a rank 1 ndarray that contains floats but forcing them to become int64
x = np.array([1.0,2.0,3.0], dtype=np.int64)

# We print the dtype of each ndarray
print('The elements in x are of type:', x.dtype)

The elements in x are of type: int64


### Save the NumPy array to a File and then read it back

In [69]:
# We create a rank 1 ndarray
x = np.array([1, 2, 3, 4, 5])

# We save x into the current directory as 
np.save('x', x)

In [71]:
# We load the saved array from our current directory into variable y
y = np.load('x.npy')

# We print y
print()
print('y = ', y)
print()

# We print information about the ndarray we loaded
print('y is an object of type:', type(y))
print('The elements in y are of type:', y.dtype)


y =  [1 2 3 4 5]

y is an object of type: <class 'numpy.ndarray'>
The elements in y are of type: int32


### Numpy ndarray using built-in functions

In [85]:
#The shape has to be a tuple
shape = (2,3)

x = np.zeros(shape)
print(x)
print("dtype: ", x.dtype)

[[0. 0. 0.]
 [0. 0. 0.]]
dtype:  float64


In [90]:
x = np.zeros(shape, dtype=np.int64)
print(x)
print("dtype: ", x.dtype)

[[0 0 0]
 [0 0 0]]
dtype:  int64


In [94]:
# Fill the array using just 1s
x = np.ones(shape, dtype=np.int64)
print(x)
print("dtype: ", x.dtype)

[[1 1 1]
 [1 1 1]]
dtype:  int64


In [97]:
# Fill the array using constants
x = np.full(shape, 5)
print(x)
print("dtype: ", x.dtype)

[[5 5 5]
 [5 5 5]]
dtype:  int32


In [99]:
# Fill the array using constants
x = np.full(shape, 5.0)
print(x)
print("dtype: ", x.dtype)

[[5. 5. 5.]
 [5. 5. 5.]]
dtype:  float64


In [103]:
# Fill the array using constants
x = np.full(shape, "hello")
print(x)
print("dtype: ", x.dtype)

[['hello' 'hello' 'hello']
 ['hello' 'hello' 'hello']]
dtype:  <U5


### Identity Matrix
Contains 1 along the diagonal

In [109]:
# Eye creates a square matrix, so passing of 5 means a matrix of shape(5, 5) with 1s along the diagonal gets created
x = np.eye(5)
print(x)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [111]:
# The list when passed would be present in the diagonal 
# and the lenght of the list would become the shape of the matrix as square matrix

x = np.diag([10, 20, 30])
print(x)

[[10  0  0]
 [ 0 20  0]
 [ 0  0 30]]


### Arange - To create matrix with numbers

In [115]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [116]:
x = np.arange(5, 10)
print(x)

[5 6 7 8 9]


In [117]:
x = np.arange(5, 100, 5)
print(x)

[ 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [119]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, like=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : integer or real, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : integer or real
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off 

### linspace - Create an array with equally spaced values

In [148]:
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that 

In [138]:
x = np.linspace(1, 25, num=7)
print(x)

[ 1.  5.  9. 13. 17. 21. 25.]


In [139]:
x = np.linspace(1, 25, num=7, endpoint=False)
print(x)

[ 1.          4.42857143  7.85714286 11.28571429 14.71428571 18.14285714
 21.57142857]


### Change the Dimensions

In [147]:
x = np.arange(20)
print(x)
print("\nshape: ", x.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

shape:  (20,)


In [149]:
x = np.reshape(x, (5, 4))
print(x)
print("\nshape: ", x.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]

shape:  (5, 4)


In [151]:
# Create array
x = np.arange(20)

# Change the shape
x = x.reshape((5, 4))
print(x)
print("\nshape: ", x.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]

shape:  (5, 4)


### random - Create ndarray with random values

In [155]:
help(np.random.random)

Help on built-in function random:

random(...) method of numpy.random.mtrand.RandomState instance
    random(size=None)
    
    Return random floats in the half-open interval [0.0, 1.0). Alias for
    `random_sample` to ease forward-porting to the new random API.



In [165]:
x = np.random.random((3,3))
print(x)

[[0.10392463 0.0495523  0.49351957]
 [0.15043654 0.36206618 0.46597246]
 [0.85157067 0.30467305 0.13498677]]


In [168]:
# Create ndarray of shape 10 x 10 with start as 1 (inclusive) and stop as 100 (exclusive)
x = np.random.randint(1, 100, (10,10))
print(x)

[[33 26 50 76 76 57  1 74 66 17]
 [48  7 87 52 47 22 53 34 67 84]
 [10 85  5 73  3 28 78 57 18 81]
 [24 78 19 13 43 14  9 48 71 82]
 [86 87 41 90  6  6  8 31 54 55]
 [56 91 90 18 96 15 13 95 19 52]
 [70 41  3 40 38 44 69  8 11 98]
 [11 22 63 23 67  4 30  2 23  9]
 [93 83 37 92 23 75 16 45 57 27]
 [22 65  4  7 11  6 75  9 63 65]]


In [170]:
help(np.random.normal)

Help on built-in function normal:

normal(...) method of numpy.random.mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    .. note::
        New code should use the ``normal`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution

In [189]:
x = np.random.normal(loc=0, scale=0.25, size=(5, 5))
print(x)
print("mean: ", x.mean())
print("std: ", x.std())
print("min: ", x.min())
print("max: ", x.max())

[[-0.12938296  0.31927413  0.16464757  0.22589022  0.12897991]
 [ 0.02304656 -0.21736191 -0.48285167  0.06880245  0.0405828 ]
 [-0.39691819  0.51539392 -0.27974925 -0.245192    0.20294637]
 [ 0.29547502  0.01083145  0.18987598  0.27767227  0.00617368]
 [ 0.14168365 -0.02761444  0.07094087 -0.27531326  0.3702932 ]]
mean:  0.039925054844481694
std:  0.245197145970111
min:  -0.4828516718402335
max:  0.5153939160202535


In [207]:
print((x>0).sum())
print((x<0).sum())

100000000
0


### 3D Array

In [209]:
# Create array
x = np.arange(27)

# Change the shape
x = x.reshape((3, 3, 3))
print(x)
print("\nshape: ", x.shape)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

shape:  (3, 3, 3)


In [212]:
x[0]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [214]:
x[0][1]

array([3, 4, 5])

In [220]:
x[0][1][2]

5

### Accessing, Deleting, and Inserting Elements Into ndarrays

#### Accessing and Modifying

In [221]:
x = np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


In [225]:
print("0th element:", x[0])
print("0th element:", x[2])
print("0th element:", x[4])

0th element: 1
0th element: 3
0th element: 5


In [228]:
print("0th element:", x[-5])
print("0th element:", x[-3])
print("0th element:", x[-1])

0th element: 1
0th element: 3
0th element: 5


In [232]:
x = np.arange(0, 12).reshape(4, 3)
print(x)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [234]:
print("x[0,0]:", x[0,0])
print("x[1,2]:", x[1,2])

x[0,0]: 0
x[1,2]: 5


In [238]:
x[1,2] = 50
print(x)

[[ 0  1  2]
 [ 3  4 50]
 [ 6  7  8]
 [ 9 10 11]]


#### Deleting

In [240]:
x = np.arange(0, 12)
print(x)

x = np.delete(x, [0, 4, 7])
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 1  2  3  5  6  8  9 10 11]


In [248]:
x = np.arange(0, 9).reshape(3, 3)
print("x=\n", x)

# Delete Row
y = np.delete(x, [0], axis=0)
print("\ny=\n",y)

# Delete Column
z = np.delete(x, [0], axis=1)
print("\nz=\n",z)

# Delete Multiple rows
w = np.delete(x, [0, 2], axis=0)
print("\nw=\n",w)

# Delete Multiple columns
h = np.delete(x, [0, 2], axis=1)
print("\nh=\n",h)


x=
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

y=
 [[3 4 5]
 [6 7 8]]

z=
 [[1 2]
 [4 5]
 [7 8]]

w=
 [[3 4 5]]

h=
 [[1]
 [4]
 [7]]


#### Appending Rows and Columns at the end

In [249]:
x = np.arange(12)
print(x)

x = np.append(x, [15, 16])
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11 15 16]


In [263]:
x = np.arange(9).reshape(3, 3)
print("x:\n", x)

# Add Rows, note that the 2nd argument must match the shape of the original
y = np.append(x, [[9,10,11]], axis=0)
print("\ny:\n", y)

# Add columns, note that the 2nd argument must match the shape of the original
z = np.append(x, [[9],[10],[11]], axis=1)
print("\nz:\n", z)

x:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

y:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

z:
 [[ 0  1  2  9]
 [ 3  4  5 10]
 [ 6  7  8 11]]


#### Inserting Rows and Columns at desired index

In [264]:
x = np.arange(9)
print(x)

[0 1 2 3 4 5 6 7 8]


In [268]:
x = np.insert(x, 2, [30, 40])
print(x)

[ 0  1 30 40 30 40  3  4  2  3  4  5  6  7  8]


In [269]:
x = np.arange(9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [272]:
y = np.insert(x, 1, [90, 100, 110], axis=0)
print(y)

[[  0   1   2]
 [ 90 100 110]
 [  3   4   5]
 [  6   7   8]]


In [277]:
z = np.insert(x, 3, [90, 100, 110], axis=1)
print(z)

[[  0   1   2  90]
 [  3   4   5 100]
 [  6   7   8 110]]


#### Stacking array

In [278]:
x = np.arange(2)
print(x)

[0 1]


In [280]:
y = np.arange(2, 6).reshape(2,2)
print(y)

[[2 3]
 [4 5]]


In [285]:
z = np.vstack((x, y))
print(z)

[[0 1]
 [2 3]
 [4 5]]


In [288]:
z = np.hstack((x.reshape(2, 1), y))
print(z)

[[0 2 3]
 [1 4 5]]
