In [1]:
import numpy as np

1. ndarray[start:end]
2. ndarray[start:]
3. ndarray[:end]

In [4]:
x = np.arange(25).reshape(5,5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [9]:
z = x[2:6, 2:6]
print(z)

[[12 13 14]
 [17 18 19]
 [22 23 24]]


In [10]:
z = x[2:, 2:]
print(z)

[[12 13 14]
 [17 18 19]
 [22 23 24]]


In [12]:
z = x[:2, 2:]
print(z)

[[2 3 4]
 [7 8 9]]


In [14]:
z = x[:, 2:]
print(z)

[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]
 [17 18 19]
 [22 23 24]]


In [16]:
z = x[:, 2]
print(z)

[ 2  7 12 17 22]


In [18]:
z = x[:, 2:3]
print(z)

[[ 2]
 [ 7]
 [12]
 [17]
 [22]]


In [29]:
# Modifying any content in the sliced array would affect the original array as well
# The sliced array is not a clone but a view

z[2, 0] = 555
print(z)

[[ 13 555]
 [ 18  19]
 [555  24]]


In [23]:
print(x)

[[  0   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11 555  13  14]
 [ 15  16  17  18  19]
 [ 20  21  22  23  24]]


### Copy of sliced array

In [30]:
x = np.arange(25).reshape(5, 5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [31]:
z = x[2:, 3:].copy()
print(z)

[[13 14]
 [18 19]
 [23 24]]


In [32]:
z[0, 1] = 555
print(z)

[[ 13 555]
 [ 18  19]
 [ 23  24]]


In [37]:
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [38]:
z = np.copy(x[2:, 3:])
print(z)

[[13 14]
 [18 19]
 [23 24]]


In [39]:
z[0, 1] = 555
print(z)

[[ 13 555]
 [ 18  19]
 [ 23  24]]


In [41]:
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### Select particular rows and columns

In [42]:
indices = [1, 3]
print(indices)

[1, 3]


In [43]:
x = np.arange(25).reshape(5, 5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [45]:
y = x[indices, :]
print(y)

[[ 5  6  7  8  9]
 [15 16 17 18 19]]


In [46]:
y = np.diag(x)
print(y)

[ 0  6 12 18 24]


In [48]:
y = np.diag(x, k=1)
print(y)

[ 1  7 13 19]


In [50]:
y = np.diag(x, k=-1)
print(y)

[ 5 11 17 23]


#### Unique elements in ndarray

In [58]:
y = np.random.randint(1, 10, (5, 5))
print(y)

[[4 7 9 1 4]
 [9 8 7 5 9]
 [8 1 7 4 1]
 [3 6 2 2 7]
 [4 4 3 7 8]]


In [59]:
z = np.unique(y)
print(z)

[1 2 3 4 5 6 7 8 9]
