### Boolean Indexing

In [28]:
import numpy as np

In [29]:
x = np.arange(25).reshape(5, 5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [30]:
y = x[x>15]
print(y)

[16 17 18 19 20 21 22 23 24]


In [31]:
y = x[x<5]
print(y)

[0 1 2 3 4]


In [32]:
y = x[(x<15) & (x>5)]
print(y)

[ 6  7  8  9 10 11 12 13 14]


In [33]:
x[(x<15) & (x>5)] = -1
print(x)

[[ 0  1  2  3  4]
 [ 5 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [15 16 17 18 19]
 [20 21 22 23 24]]


### Sorting

In [34]:
x = np.random.randint(1, 5, size=(25, ))
print(x)

[1 3 2 2 4 1 4 3 3 2 4 1 4 4 3 4 4 4 2 2 2 4 2 3 1]


In [36]:
# Tis type sorts the array by creating a copy
y = np.sort(x)
print(y)
print(x)

[1 1 1 1 2 2 2 2 2 2 2 3 3 3 3 3 4 4 4 4 4 4 4 4 4]
[1 3 2 2 4 1 4 3 3 2 4 1 4 4 3 4 4 4 2 2 2 4 2 3 1]


In [37]:
# This type sorts the elements in place
x.sort()
print(x)

[1 1 1 1 2 2 2 2 2 2 2 3 3 3 3 3 4 4 4 4 4 4 4 4 4]


In [41]:
x = np.random.randint(1, 25, size=(5, 5))
print(x)

[[20 14 19 15 19]
 [ 3 20  9 16  1]
 [ 9 17  8  4 20]
 [24 21 17  6  7]
 [ 8  2  6 13  6]]


In [44]:
# Sorts rows wise
y = np.sort(x, axis=0)
print(y)

[[ 3  2  6  4  1]
 [ 8 14  8  6  6]
 [ 9 17  9 13  7]
 [20 20 17 15 19]
 [24 21 19 16 20]]


In [46]:
# Sorts column wise
y = np.sort(x, axis=1)
print(y)

[[14 15 19 19 20]
 [ 1  3  9 16 20]
 [ 4  8  9 17 20]
 [ 6  7 17 21 24]
 [ 2  6  6  8 13]]


### Set Operations

In [48]:
# We create a rank 1 ndarray
x = np.array([1,2,3,4,5])

# We create a rank 1 ndarray
y = np.array([6,7,2,8,4])

# We print x
print()
print('x = ', x)

# We print y
print()
print('y = ', y)

# We use set operations to compare x and y:
print()
print('The elements that are both in x and y:', np.intersect1d(x,y))
print('The elements that are in x that are not in y:', np.setdiff1d(x,y))
print('All the elements of x and y:',np.union1d(x,y))


x =  [1 2 3 4 5]

y =  [6 7 2 8 4]

The elements that are both in x and y: [2 4]
The elements that are in x that are not in y: [1 3 5]
All the elements of x and y: [1 2 3 4 5 6 7 8]


### Quiz

In [54]:
import numpy as np

# Create a 5 x 5 ndarray with consecutive integers from 1 to 25 (inclusive).
# Afterwards use Boolean indexing to pick out only the odd numbers in the array

# Create a 5 x 5 ndarray with consecutive integers from 1 to 25 (inclusive).
X = np.arange(1, 26).reshape(5, 5)
print(X)

# Use Boolean indexing to pick out only the odd numbers in the array
Y = X[X%2==1]
print(Y)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25]


### Arithmetic operations and Broadcasting


In [60]:
x = np.array([1,6,3,4,3])
y = np.array([4,2,3,2,5])
print(x)
print(y)

[1 6 3 4 3]
[4 2 3 2 5]


In [61]:
print(x+y)
print(np.add(x, y))

[5 8 6 6 8]
[5 8 6 6 8]


In [63]:
print(x-y)
print(np.subtract(x, y))

[-3  4  0  2 -2]
[-3  4  0  2 -2]


In [64]:
print(x*y)
print(np.multiply(x, y))

[ 4 12  9  8 15]
[ 4 12  9  8 15]


In [66]:
print(x/y)
print(np.divide(x, y))

[0.25 3.   1.   2.   0.6 ]
[0.25 3.   1.   2.   0.6 ]


### 2D Array

In [70]:
x = np.array([3,2,8,4]).reshape(2, 2)
y = np.array([1,3,5,4]).reshape(2, 2)
print(x)
print(y)
print(x+y)
print(x-y)
print(x*y)
print(x/y)

[[3 2]
 [8 4]]
[[1 3]
 [5 4]]
[[ 4  5]
 [13  8]]
[[ 2 -1]
 [ 3  0]]
[[ 3  6]
 [40 16]]
[[3.         0.66666667]
 [1.6        1.        ]]


In [72]:
print(x)
print(np.sqrt(x))

[[3 2]
 [8 4]]
[[1.73205081 1.41421356]
 [2.82842712 2.        ]]


In [74]:
print(np.power(x, 2))

[[ 9  4]
 [64 16]]


In [76]:
print(np.exp(x))

[[  20.08553692    7.3890561 ]
 [2980.95798704   54.59815003]]


In [91]:
print(x)
print(np.mean(x))
print(np.mean(x, axis=0))
print(np.mean(x, axis=1))

[[3 2]
 [8 4]]
4.25
[5.5 3. ]
[2.5 6. ]


In [90]:
print(np.min(x))
print(np.min(x, axis=0))
print(np.min(x, axis=1))

2
[3 2]
[2 4]


In [88]:
print(np.max(x))

8


In [87]:
print(np.std(x))

2.277608394786075


In [93]:
print(np.median(x))

3.5


In [94]:
print(x)

[[3 2]
 [8 4]]


In [95]:
print(x+2)

[[ 5  4]
 [10  6]]


In [96]:
print(x-3)

[[ 0 -1]
 [ 5  1]]


In [98]:
print(x*4)

[[12  8]
 [32 16]]


### Broadcasting

In [99]:
print(x)

[[3 2]
 [8 4]]


In [100]:
y = np.array([1, 2])
print(y)

[1 2]


In [101]:
print(x+y)

[[4 4]
 [9 6]]


In [105]:
y = y.reshape(2, 1)
print(y)

[[1]
 [2]]


In [106]:
print(x+y)

[[ 4  3]
 [10  6]]
