In [28]:
import numpy as np

In [29]:
X = np.array([1,2,3,4,5])
print(X)

[1 2 3 4 5]


In [30]:
Y = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(Y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
print(np.delete(X, [0,4]))

[2 3 4]


In [34]:
print(np.delete(Y, 0, axis=0))

[[4 5 6]
 [7 8 9]]


In [36]:
print(np.delete(Y, [0,1], axis=0))

[[7 8 9]]


In [39]:
print(np.delete(Y, [0,1], axis=1))

[[3]
 [6]
 [9]]


In [41]:
print(np.append(X, [7,8]))

[1 2 3 4 5 7 8]


In [44]:
print(np.append(Y, [[10,11,12]], axis=0))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [48]:
print(np.append(Y, [[10],[11],[12]], axis=1))

[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]


In [51]:
print(np.insert(X, 0, [1,2]))

[1 2 1 2 3 4 5]


In [54]:
print(np.insert(Y,0,[10,11,12], axis=0))

[[10 11 12]
 [ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [57]:
print(np.insert(Y,1,[10,11,12], axis=1))

[[ 1 10  2  3]
 [ 4 11  5  6]
 [ 7 12  8  9]]


In [63]:
print(np.vstack(([20,21,22], Y)))

[[20 21 22]
 [ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [64]:
print(np.hstack(([[20],[21],[22]], Y)))

[[20  1  2  3]
 [21  4  5  6]
 [22  7  8  9]]
