In [8]:
import numpy as np

In [9]:
X = np.arange(20).reshape(4,5)
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [10]:
new_X = X[2:, 3:]
print(new_X)

[[13 14]
 [18 19]]


In [11]:
new_X[0,0]= 200
print(new_X)
print(X)

[[200  14]
 [ 18  19]]
[[  0   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12 200  14]
 [ 15  16  17  18  19]]


In [13]:
X = np.arange(20).reshape(4,5)
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [14]:
new_X = X[2:, 3:].copy()
print(new_X)

[[13 14]
 [18 19]]


In [15]:
new_X[0,0]= 200
print(new_X)
print(X)

[[200  14]
 [ 18  19]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [16]:
X = np.arange(20).reshape(4,5)
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [17]:
new_X = np.diag(X)
print(new_X)

[ 0  6 12 18]


In [18]:
new_X = np.diag(X, k=1)
print(new_X)

[ 1  7 13 19]


In [20]:
new_X = np.diag(X, k=-1)
print(new_X)

[ 5 11 17]


In [21]:
X = np.array([[1,2,3],[5,2,8],[1,2,3]])
print(np.unique(X))

[1 2 3 5 8]
