In [7]:
import numpy as np

In [8]:
X = np.arange(1,21).reshape(4,5)
print(X)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [12]:
new_X = X[1:4, 2:5]
print(new_X)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [14]:
new_X = X[1:, 2:]
print(new_X)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [18]:
new_X = X[:2, :3]
print(new_X)

[[1 2 3]
 [6 7 8]]
